config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end

  root to: 'pages#home'

  resources :users, except: [:delete] do
    resources :bookings, except: [:delete]
    resources :reviews, except: %i[edit update delete]
    resources :room_messages
    resources :rooms

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  DOGBREEDS = ["Labrador Retriever", "German Shepherd", "Golden Retriever", "Beagle", "French Bulldog", "Yorkshire Terrier", "Poodle"]
  belongs_to :user
  belongs_to :walker, class_name: "User"

  validates :pet, presence: true, inclusion: { in: DOGBREEDS }
  validates :date, presence: true
  validates :starting_time, presence: true
  validates :end_time, presence: true
  validates :address, presence: true
  
  # attr_accessible :address , :latitude , :longitude 
  geocoded_by :address 
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    # @bookings = Booking.all
    @bookings = policy_scope(Booking)
    @user = current_user
    @users = User.where(username: @user.username)
    @markers = markers
    # raise
    if Rails.env.production?
      @country = request.location.country_code
      @city = request.location.city
    end
  end

  def show
    @booking = Booking.find(params[:id])
    # @booking.user = current_user
    #@booking.walker = User.find(booking_params)
    @bookings = Booking.where(user_id: current_user.id, walker_id: @booking.walker_id)
    # @users = User.where(username: current_user.username)
    # @markers = markers
    @booking_markers = booking_markers
    authorize @booking
  end

  def ip
    @geocoder_result = request.location
    raise
  end

  def new
    @booking = Booking.new
    @user = User.find(params[:user_id])
    authorize @booking
  end

  def create
    @user = User.find(params[:user_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.walker = @user
    authorize @booking

    if @booking.save

      redirect_to user_bookings_path(@booking)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :walker_id, :booking_id, :pet, :date, :end_time, :starting_time, :address, :comment)
  end

  def markers
    @users.geocoded.map do |user|
      # if user != @user
        {
          lat: user.latitude,
          lng: user.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { user: user })
          # image_url: helpers.asset_url('optional: add image file from assets')
        }
      # end
    end
  end
  def booking_markers
    @bookings.geocoded.map do |booking|
        {
          lat: booking.latitude,
          lng: booking.longitude,
          # infoWindow: render_to_string(partial: "info_window", locals: { user: user })
          # image_url: helpers.asset_url('optional: add image file from assets')
        }
      # end
    end
  end
end

app/views/bookings/_info_window.html.erb
<h2><%= user.username %></h2>
<p><%= user.address %></p>

app/views/bookings/index.html.erb
<div class="row">
  <h1><%= link_to 'NewBooking', new_user_booking_path(current_user.id)%>   </h1>
  <ul>
    <%   @bookings.each do |booking| %>
      <li> Your walker is: <%= booking.walker.username  %></li>
      <li> For your: <%= booking.pet  %></li>
      <li> On <%= booking.date %> </li>
      <li> Starts at <%= booking.starting_time %> </li>
      <li> Ends at <%= booking.end_time %> </li>
      <li> Your pick up address is <%= booking.address %> </li>
      <li><%= link_to 'View Booking', user_booking_path(@user, booking) %></li>
    <% end %>
  </ul>
</div>
<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@user, @booking] do |f| %>
  <%= f.association :walker %>
  <%= f.input :pet, collection: ["Labrador Retriever", "German Shepherd",  "Golden Retriever", "Beagle", "French Bulldog", "Yorkshire Terrier", "Poodle"] %>
  <%= f.input :date, as: :date, html5: true %>
  <%= f.input :starting_time, as: :time, html5: true %>
  <%= f.input :end_time, as: :time, html5: true %>
  <h2>Your address, or a specific pick up location
  </h2>
  <%= f.input :address, as: :string, html5: true %>
  <h2>Please put any comment</h2>
  <%= f.input :comment, as: :string, html5: true %>
  <%= f.submit "Confirm booking", class: "btn btn-primary" %>
<% end %>
<%= link_to "Back", user_path(@user) %>

app/views/bookings/show.html.erb
<h1>Your booking </h1>
<h2>Your walker is: <%= @booking.walker.username %></h2>
<h2>Your name: <%= @booking.user.username %></h2>
<h2> <%= link_to "Go to your walker's profile", user_path(@booking.walker)%> </h2>
<h2>Booking for your <%= @booking.pet %> </h2>

<p>
User Location: <%= @country %><br />
User City: <%= @city %><br />
</p>

<%# <%= button "Here I am", :controller => :bookings, :action => :ip, class: 'btn btn-danger' %>

<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @booking_markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>