config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end

  root to: 'pages#home'

  resources :users, except: [:delete] do
    resources :bookings, except: [:delete]
    resources :reviews, except: %i[edit update delete]
    resources :room_messages
    resources :rooms

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :bookings_received, class_name: 'Booking', foreign_key: :walker_id
  has_many :reviews
  has_many :reviews_written, class_name: 'Review', foreign_key: :reviewer_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true, uniqueness: true
  validates_format_of :username, with: /^[a-zA-Z0-9_.]*$/, multiline: true
  validate :validate_username

  has_one_attached :avatar
  has_one_attached :pet_avatar

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  def login
    @login || username || email
  end

  def gravatar_url
    gravatar_id = Digest::MD5.hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value",
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = policy_scope(User)
    @markers = markers
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @room = Room.new
    @result = request.safe_location
    authorize @room
    # @marker = markers
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    @pets = ["Dog1", "Dog2", "Dog3"]
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  private



  def user_params
    params.require(:user).permit(:id, :bio, :avatar, :username, :address, :pet, :pet_avatar, :room)
  end

  def markers
    if !@users.nil?
      @users.geocoded.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { user: user })
          # image_url: helpers.asset_url('optional: add image file from assets')
        }
      end
      #else
      #  @user.geocode.map do |user|
      #    {
      #      lat: user.first,
      #      lng: user.last,
      #      infoWindow: render_to_string(partial: "info_window", locals: { user: user })
      # image_url: helpers.asset_url('optional: add image file from assets')
      #    }
      #  end
    end
  end
end

app/views/users/_form.html.erb
<%= simple_form_for [@user, @room] do |form| %>
  <%= form.submit "Chat", class: 'btn btn-success' %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h1 class="text-center mt-4">Edit Your Account</h1>

      <%= simple_form_for @user, url: user_path(@user) do |f| %>
      <%# <%= form_for(:user, :url => session_path(:user)) do |f| %>

      <div class="form-group">
        <div class="ml-5 mt-5 row">
          <div class="col-sm-3">
            <% if resource.avatar.attached? %>
              <%= image_tag resource.avatar.variant(resize: "100x100!"), class: "rounded-circle" %>
            <% else %>
              <%= image_tag gravatar_image_url(current_user.email, size: 100), height: 100, width: 100, class: "rounded-circle" %>
            <% end %>
          </div>

          <div class="col-sm-8 d-flex justify-content-center align-items-center">
            <%= f.file_field :avatar %>
          </div>
        </div>
      </div><br>

      <%= f.input :username %>
      <%= f.input :bio, :input_html => {:rows => 7}  %>
      <%= f.input :address %>
      <%= f.input :pet, collection: @pets%>
      <%= f.button :submit, "Confirm details" %>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Now Available to Walk Your Dog</h1>
<div class="container">
  <ul class="list-group">
    <% @users.each do |user| %>
      <%# map still shows current_user on line 13 %>
      <%# if user != current_user %>
      <li class="list-group-item"><%= link_to user.username, user_path(user) %> <%= user.address %></li>
      <%# end %>
    <% end %>
  </ul>
<br />
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/users/show.html.erb
<div class="ml-5 mt-5 mb-5">
  <div class="d-flex">
    <% if resource.avatar.attached? %>
      <%= image_tag resource.avatar.variant(resize: "100x100!"), class: "rounded-circle" %>
    <% else %>
      <%= image_tag gravatar_image_url(current_user.email, size: 100), height: 100, width: 100, class: "rounded-circle" %>
    <% end %>
  </div>
  <h1> <%= @user.username %></h1>
  <h4>and their dog, <%= "#{@user.pet}!" %></h4>
  <% if @user.pet_avatar.attached? %>
    <%= image_tag @user.pet_avatar, style: "width: 200px; display:block;" %>
  <% end %>
</div>

<%= link_to 'Leave a review', new_user_review_path(@user) %>
<ul class="list-group">
  <% @user.reviews.each do |review| %>
    <li class="list-group-item"><%= review.comment %></li>
  <% end %>
</ul>
<p><%= @request %></p>
<% if @user == current_user %>
  <%= link_to 'Your bookings', user_bookings_path(@user) %>
<% end %>
<%= link_to 'Book this walker now', new_user_booking_path(@user) %>
<%= link_to 'Back to walkers search', users_path %>
<%# Map here for debugging purposes currently %>
<div class="mb-3">
  <%= render partial: 'form' %>
</div>
<br />
<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<br />

<% unless current_user %>
<div class="ml-3 mt-5">
  <div class="row">
    <div class="col-md-8">
      <h1>Add your dog's photo!</h1>
      <%= form_with(model: @user, local: true, class: "w-25") do |form| %>

      <div class="form-group">
        <%= form.label :pet %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :pet_avatar %>
        <%= form.file_field :pet_avatar, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.submit controller.action_name.capitalize + " Pet", class: "btn btn-primary" %>
      </div>

      <% end %>
    </div>
  </div>
</div>
<% end %>

<%# Some old code: %>
<%# <div class="ml-3 mt-5">
  <div class="row">
    <div class="col-md-8">
      <h1>Add Photo</h1>
      <%= simple_form_for @user do |f| %>
        <%# <%= f.input :pet, class: "form-control" %>

          <%# <%= f.input :pet_avatar, as: :file, class: "form-control" %>

        <%# <%= f.button :submit, "Upload", class: 'btn btn-primary' %>
      <%# <% end %>
      <%# <br>
    </div>
  </div>
</div> %>
<%# Display pet picture %>
<%# <%= image tag @user.pet, height: 300, width: 400, crop: :fill %>